src\_pytest\outcomes.py::_WithException
